"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# =========================================================
#  I. IMPORT SECTION
# =========================================================
import os
from pathlib import Path

# =========================================================
#  II. PATH DEFINITION
# =========================================================
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ang PROJECT_DIR ay ang folder ng 'portfolio' (project settings/urls.py)
# Ito ay ginagamit na ngayon ng BASE_DIR, kaya maaaring tanggalin ang PROJECT_DIR.
# Ginagamit ang os.path.join para sa mas lumang style paths kung kinakailangan.


# =========================================================
#  III. SECURITY & DEBUGGING
# =========================================================
SECRET_KEY = 'django-insecure-gs56q0bt(39xgv8@ya%63-cso!0houq)y)i-4lho+l7v!uj=rb'
DEBUG = True
ALLOWED_HOSTS = []


# =========================================================
#  IV. APPLICATION DEFINITION
# =========================================================

INSTALLED_APPS = [
    # Django Admin at Built-in Apps (Mas maganda kung uunahin ito)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # Para sa mas madaling basahin na numero (e.g., 1000 -> 1k)

    # Iyong Custom Apps (Ang 'posts' app)
    'posts', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio.urls'


# =========================================================
#  V. TEMPLATE CONFIGURATION (Inayos)
# =========================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        # Inayos ang DIRS: Dapat isang listahan lang ng paths ang DIRS.
        # Ginagamit natin ang BASE_DIR / 'templates' para sa global templates.
        'DIRS': [
            BASE_DIR / 'templates',
            # Maaaring tanggalin ang ibang os.path.join kung gumagamit ka ng pathlib
        ], 
        
        'APP_DIRS': True, # KRITIKAL: Pinapahanap nito ang templates sa loob ng bawat app/templates folder (e.g., posts/templates)

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# =========================================================
#  VI. DATABASE CONFIGURATION (PostgreSQL)
# =========================================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "portfolio",
        "USER": "postgres",
        "PASSWORD": "12345", # Tiyakin na ito ay tama at private sa production!
        "HOST": "127.0.0.1",
        "PORT": "5432",
        "ATOMIC_REQUESTS": True,
        "CONN_MAX_AGE": 0,
        "CONN_HEALTH_CHECKS": False,
        "OPTIONS": {
            "client_encoding": "UTF8",
        },
    },
}


# =========================================================
#  VII. PASSWORD VALIDATION & AUTHENTICATION
# =========================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Set the redirect URL after login/logout
LOGIN_REDIRECT_URL = '/' # Idirekta sa home page pagkatapos mag-login
LOGOUT_REDIRECT_URL = '/' # Idirekta sa home page pagkatapos mag-logout


# =========================================================
#  VIII. INTERNATIONALIZATION
# =========================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =========================================================
#  IX. STATIC AND MEDIA FILES (Tiyakin na tama ang paths)
# =========================================================
# NOTE: Ang paggamit ng os.path.join at os.path.dirname ay maayos, 
# ngunit dapat mo ring tiyakin na tama ang structure ng iyong folders.

STATIC_URL = '/static/'

# STATICFILES_DIRS: Dito hahanapin ni Django ang karagdagang static files (e.g., global CSS/JS)
STATICFILES_DIRS = [
    BASE_DIR / 'static', 
    # Sa halip na mag-rely sa os.path.dirname(BASE_DIR) na posibleng maging malabo
]

# STATIC_ROOT: Dito kokopyahin ng 'collectstatic' ang LAHAT ng static files (para sa production)
STATIC_ROOT = BASE_DIR / 'staticfiles_cdn' 

# MEDIA FILES (Para sa mga uploads ng user, tulad ng iyong Post image)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================
#  X. DEFAULT CONFIG
# =========================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'